### ISSUE TITLE
FileSystem.AddFileAsync generates unexpected hashes for larger files

### ISSUE THREAD

**Issue by Jonax** [richardschneider/net-ipfs-engine#125] opened 2019-07-06 02:08 UTC
With a default configuration, FileSystem.AddFileAsync() appears to return a different hash than expected when the file in question is above a specific size threshold.  

Based on local trial & error, this threshold appears to be exactly 43.5 MB (45613056 bytes) - Any file exactly this size or smaller should return a hash identical to an equivalent `add -n` operation in go-ipfs.  Files larger than this will result in a different hash than go-ipfs provides.  

This behaviour doesn't seem to trigger test `AddFile_Large`, since `star_trails.mp4` is below this threshold (37.8MB).  Replacing the file with a file larger than 44MB should cause the test to error on the hash assert in the first half of the test.

**Comment by richardschneider** [comment] 2019-07-06 03:11
Thanks, that is a very good bug report.  I'll investigate.

**Comment by richardschneider** [comment] 2019-07-06 03:15
@Jonax What version of go-ipfs are you testing against?

**Comment by Jonax** [comment] 2019-07-06 03:38
0.4.21, Windows x64 (go-ipfs_v0.4.21_windows-amd64.zip)

**Comment by richardschneider** [comment] 2019-07-08 01:15
The issue is with generating a [balanced tree](https://github.com/ipfs/specs/tree/master/unixfs#layout).  Need to change to `net-ipfs-engine` to only generate up to 174 blocks per unixfs node.

**Comment by richardschneider** [comment] 2019-07-13 02:11
@Jonax Sorry it took so long to get this working.  I've added the test `AddFile_Larger`.  I'll make a release in a few hours.

**Comment by richardschneider** [comment] 2019-07-13 03:05
Fixed in [release v0.11.0](https://github.com/richardschneider/net-ipfs-engine/releases/tag/v0.11.0)

**Closed by richardschneider** 2019-07-13 03:05 UTC

**Comment by Jonax** [comment] 2019-07-13 07:32
Tested with local live files of increasing 2^n file sizes up to 1GB.  All passed with expected hashes.  

I'd call this bug well & truly fixed.  Nice job.
